apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: deployments-autosync
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/sailorartemis/minikube.git
        revision: HEAD
        directories:
          - path: "../deployments/*"
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/sailorartemis/minikube.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true